### ISSUE TITLE
[design]  Migrar CSS do Mapa Cultural Design para Aurora.

### ISSUE THREAD

**Issue by saracamilo** [secultce/aurora-ui#63]
## WHAT

Importar e adaptar o CSS utilizado no projeto Mapa Cultural Design para o projeto Aurora, garantindo consistência visual e funcionalidade no novo ambiente.

## CHECKLIST

- [x] Trazer /colors.css
- [x] /card.css
- [ ] ./editor.css
- [ ] ./forms.css
- [x] /layout.css
- [ ] /navigation.css
- [x] timeline.css

**Comment by alessandrofeitoza** [comment]
Fixed by #62
